### ISSUE TITLE
[FEATURE] OBS Event Support

### ISSUE THREAD

**Issue by Gnaj** [xXLaokoonXx/LoLTainer#23]
Would it be possible for event triggers hotkey combination, ahk file or obs web socket event?

This would be awesome for enchancing streams something like, whenever you make a pentakill or a double you could send custom visuals or even audio but trough obs or a script

**Comment by xXLAOKOONXx** [comment]
I am not into OBS WebSocket yet.
The idea sounds nice!
As you seem kinda experienced around OBS do you know some good documentation of OBS Apis or even know of a C# Library or Framework to use?
Additional question:
Are you more interested in player streams or more looking towards casting?

**Comment by Gnaj** [comment]
> I am not into OBS WebSocket yet.
> The idea sounds nice!
> As you seem kinda experienced around OBS do you know some good documentation of OBS Apis or even know of a C# Library or Framework to use?
> Additional question:
> Are you more interested in player streams or more looking towards casting?

Here is the OBS Websocket C# library https://github.com/BarRaider/obs-websocket-dotnet this is as far as i would go since i dont know the first thing about coding but i hope it helps!

Also, i personally  am more interested in streaming the game, i think such integration could lead to very entertaining features maybe toggling a black n white filter on the camera when player dies, or like i mentioned triggering diferent video sources depending on the kill streak of the player. 

Also also, if such integration isnt out right possible, instead of sending audiofiles, sending keystrokes, batfiles, ahk or something else that allow user to program the action depending on the event/action.

Anyway these are just some thoughts im sure there are many more, let me know if i can contribute with something and i will try my best !

**Comment by xXLAOKOONXx** [comment]
Thanks, I will dig into it.
I guess I need to figure out some nice architecture to support different Outputs as OBS, SoundPlayer, KeyPress or similar.
I will also loop back to Riot whether this is fine with them (about KayPress I am quite unsure).
After I figured out some architectural approach I will dig into what OBS Api supports and then come back to ask for some first UseCase to start with. This UseCase you could provide then :)

**Comment by xXLAOKOONXx** [comment]
@Gnaj 
I refactored almost the whole code base in develop branch.
The App should work just as before but with the option for me to add new Consumers such as OBS.
I need to do some clean up, redo the documentation and do some proper testing.
But after those steps are done I can start implementing OBS Support.
Therefore I am looking for some first examples.
One I came up with: "When I go InGame I would love the LoLTainer to switch to a specific scene"
The more information I get on those examples the better I can implement them.
The easiest OBS Actions I found was: Switching Scene and setting visibility of scene item.

**Comment by Gnaj** [comment]
Hello ! that was fast tho! i'd love to try it ! i think for the type of integration, switch scene, turn on and of a source, or turn on and off a source filter. Some example for this could be like
"Whe player dies - Turn on/off camera source filter" - in order to make like a black and white death screen or active some shader idk

Also if possible, "When player kill someone, make a source visible", this could be the same as for the replay system, if player idk kill or assist 1+, save a replay after a couple of seconds (i dont think this is on the API but can be done by sending the key for it)"

what events can your software detect? maybe dragons or baron?

**Comment by xXLAOKOONXx** [comment]
Yeah I kinda grinded some nights^^
I will start with Switching Scene for sure as I already tested that one out and now I have some next points to go to.
Current List of Events: https://github.com/xXLaokoonXx/LoLTainer/blob/develop/documentation/user/Events.md

**Comment by xXLAOKOONXx** [comment]
Big point on my agenda is approval by riot that the direction this app is heading is fine with them.
They are contacted and I wait for response. Based on their available time this might take some days or weeks.

**Comment by Gnaj** [comment]
> Yeah I kinda grinded some nights^^
> I will start with Switching Scene for sure as I already tested that one out and now I have some next points to go to.
> Current List of Events: https://github.com/xXLaokoonXx/LoLTainer/blob/develop/documentation/user/Events.md

Nice! those client events can do wonders for stream automation, also idk much about github etiquete but maybe this project can help https://github.com/ar414-com/pansen-panel its a live game scoreboard but i think it have all the turrets, dragons by type etc implemented, maybe that can help somehow.

hopefully they approve it it would be a great way to add stuning visuals to streams

as for rn is it possible to test the current version?

**Comment by xXLAOKOONXx** [comment]
official version w riot approval: https://github.com/xXLaokoonXx/LoLTainer/releases/tag/v1.0.1
current alpha testing: https://github.com/xXLaokoonXx/LoLTainer/releases/tag/dev
**both do not support OBS yet**
alpha has new schema and design, but might lack some testing and a shutdown on closing the window 😄

**Comment by xXLAOKOONXx** [comment]
I seem to have fixed this in #25 so lets clean up and close this issue
